export enum PositionEnum {
    Forward = 'F',
    Defense = 'D',
    Goalie = 'G',
}

export enum TeamEnum {
    BuffaloSabres = 'Buffalo Sabres',
    BostonBruins = 'Boston Bruins',
    DetroitRedWings = 'Detroit Red Wings',
    FloridaPanthers = 'Florida Panthers',
    MontrealCanadiens = 'Montreal Canadiens',
    OttawaSenators = 'Ottawa Senators',
    TampaBayLightning = 'Tampa Bay Lightning',
    TorontoMapleLeafs = 'Toronto Maple Leafs',
    ColumbusBlueJackets = 'Columbus Blue Jackets',
    CarolinaHurricanes = 'Carolina Hurricanes',
    NewJerseyDevils = 'New Jersey Devils',
    NewYorkIslanders = 'New York Islanders',
    NewYorkRangers = 'New York Rangers',
    PhiladelphiaFlyers = 'Philadelphia Flyers',
    PittsburghPenguins = 'Pittsburgh Penguins',
    WashingtonCapitals = 'Washington Capitals',
    ColoradoAvalanche = 'Colorado Avalanche',
    ChicagoBlackhawks = 'Chicago Blackhawks',
    DallasStars = 'Dallas Stars',
    MinnesotaWild = 'Minnesota Wild',
    NashvillePredators = 'Nashville Predators',
    StLouisBlues = 'St Louis Blues',
    UtahMammoth = 'Utah Mammoth',
    WinnipegJets = 'Winnipeg Jets',
    AnaheimDucks = 'Anaheim Ducks',
    CalgaryFlames = 'Calgary Flames',
    EdmontonOilers = 'Edmonton Oilers',
    LosAngelesKings = 'Los Angeles Kings',
    SanJoseSharks = 'San Jose Sharks',
    SeattleKraken = 'Seattle Kraken',
    VancouverCanucks = 'Vancouver Canucks',
    VegasGoldenKnights = 'Vegas Golden Knights',
}
